# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Illegible Semantics"
description: "Companion page to alt.vis submission"
author:      "Gerrit Rijken, Rene Cutura, Frank Heyen, Michael Sedlmeier, Michael Correll, Jason Dykes, Noeska Smit"
