theme: jekyll-theme-slate
title: Illegible Semantics
tagline: Exploring the Design Space of Metal Logos
description: Companion page to the alt.vis submission
show_downloads: false
github:
  is_project_page: false
